vmware/cluster-api-upgrade-tool

pkg/internal/kubernetes/pod_exec.go, pkg/upgrade/control_plane.go
=> Eliminate etcdctl copy pasta

main.go, pkg/upgrade/config.go
* Uses cobra to mark flags as required instead of a validate method
* Validate now validates datat including valid scope
* Refactor scope and provide a better error message
=> Refactor validations

pkg/upgrade/config.go
=> Correct json tag for TargetClusterConfig.TargetApiEndpoint

main.go, pkg/upgrade/base.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go, pkg/upgrade/machine_deployment.go, pkg/upgrade/machine_image.go, pkg/upgrade/machine_image_test.go
=> Support modifying image id when upgrading.

main.go, pkg/upgrade/base.go, pkg/upgrade/config.go, pkg/upgrade/config_test.go
The test is mostly a skeleton to add to if we find it necessary to test the Boolean logic.
EDIT: The bulk of this is now test code boilerplate.
EDIT2: this conflicts with the other open PR, I don't mind fixing the conflicts whenever either of these merge.
=> restructure config

pkg/internal/kubernetes/pod_exec.go, pkg/internal/kubernetes/rest_config.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go
=> Ensure errors have stack info

main.go
=> Adds the Kubeconfig Secret CLI flag

main.go
=> Print a stack trace for errors

pkg/upgrade/control_plane.go, pkg/upgrade/control_plane_test.go
=> Switch to etcdctl v3

main_test.go
This test runs the upgrade against a 3 node control plane. it takes about 10 minutes to complete on an xl instance in aws.
`go test -count=1 -timeout 20m -v -run TestMultipleControlPlaneUpgradeScenario .`
code cleanups after idempotency work gets tested.
=> setup a test for multicp upgrade

main.go, pkg/upgrade/base.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go
=> Adds upgrade ID flag and writes annotations to upgraded nodes

pkg/logging/logrus_logr.go
=> Do a nil check on log name

README.md
=> Correct example in readme

pkg/upgrade/config.go
=> Removing MachineClass from MachineUpdateConfig

README.md
=> Correct CAPI version

go.mod, go.sum
Fixes: #106 
CAPI v0.2.6
CABPK v0.1.4
=> Update go.mod to latest CAPI, CABPK

README.md, main.go, pkg/upgrade/control_plane.go
Only the last commit is relevant - will rebase after #103 is merged
Fixes #38
=> Support a --config file

pkg/upgrade/control_plane.go
Remove requirement that machine.spec.version be populated. Remove logic
that attempts to determine if this is a minor Kubernetes version upgrade
and instead always check to see if we need to create the kubelet
configmap and rbac for the desired version.
Expand kubelet configmap/rbac logging.
Fixes #109
=> Remove machine.spec.version requirement

go.mod, main.go
=> Make CLI flags override config file values

main.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go, pkg/upgrade/control_plane_test.go
=> Require upgrade ID

.gitignore, go.sum, pkg/upgrade/control_plane.go
=> fix: remove old nodes from kubeadm configmap

main.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go
=> Use a single machine timeout when waiting

pkg/upgrade/control_plane.go
Retry machine deletion up to 5 minutes, in case the cluster's load
balancer routes the request to the machine being deleted.
Fixes #96
=> Retry machine deletion up to 5 minutes

pkg/upgrade/control_plane.go
=> Poll for machine deletion and kubeadm configmap updates

pkg/upgrade/control_plane.go
=> Check etcd cluster health before each machine

README.md, main.go, pkg/upgrade/config.go, pkg/upgrade/control_plane.go, test/integration/go.mod
=> Add kubeadm configmap patching support

pkg/upgrade/control_plane.go
System pod names are suffixed with node name, not hostname.
=> Use node name (vs hostname) to guess system pod names

pkg/upgrade/control_plane.go
In certain situations, the PodIP may not only be set to the empty
string, but it can be set to "\<nil\>". It's unclear _why_ that happens,
but until there are validations that prevent these malformed IPs from
being set, the command needs to account for this.
Rather than trying to enumerate all of the likely malformed strings,
falling back in the event of a failed parse should cover any future
scenarios as well.
Fixes #164
=> Fall back to 127.0.0.1 in etcdctl command when pod has an unparseable IP

pkg/upgrade/control_plane.go
What this PR does / why we need it:
Adds the cluster roles for Kubernetes 1.18
Which issue(s) this PR fixes
Fixes #167 
Signed-off-by: emil john <ejohn@vmware.com>
=> Support for upgrades to Kubernetes 1.18
